- name: Deploy and setup EKS cluster
  hosts: localhost
  gather_facts: no

  tasks:
    - name: import static var data
      include_vars:
        dir: ./vars/static
        ignore_unknown_extensions: True
        extensions:
          - yaml

    - name: start a bastion container
      include_tasks: ./tasks/bastion-task.yaml