- name: join clusters to hub
  hosts: localhost
  gather_facts: no
  tasks:
    - name: import static var data
      include_vars:
        dir: ./vars/static
        ignore_unknown_extensions: True
        extensions:
          - yaml

    - name: authenticate with cluster
      command: >
        aws eks get-token --region {{ eks.region }} 
          --cluster-name {{ eks.clustername }} | jq .status.token
      register: clusterauth

    - name: import dynamic var data
      include_vars:
        dir: ./vars/static
        ignore_unknown_extensions: True
        extensions:
          - yaml
