---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: gatekeeper-policyset
placementBindingDefaults:
  name: gatekeeper-policyset
policyDefaults:
  standards:
    - NIST SP 800-53
  categories:
    - CM Configuration Management
  controls: 
    - CM-2 Baseline Configuration
  namespace: "policies"  
  pruneObjectBehavior: "DeleteIfCreated"
  complianceType: "musthave"  
  evaluationInterval:
    compliant: 1m
    noncompliant: 45s  
  remediationAction: "enforce"  
  severity: "medium"
  policySets:
    - gatekeeper-policyset
  placement:
    clusterSelectors:
      environment: "dev"
      vendor: "OpenShift"

policies:
  - name: container-deny-latest-tag
    disabled: false
    manifests:
    - path: gatekeeper/container-deny-latest-tag
    
policySets:
  - description: A set of open policy agent gatekeeper admission controls that require best practices to be followed for applications being installed onto the managed cluster
    name: gatekeeper-policyset
...