resources:
- ../../base
patches:
- target:
    kind: PostgresCluster
    name: hippo
  patch: |-
    - op: replace
      path: /spec/instances/0/dataVolumeClaimSpec/resources/requests/storage
      value: "2Gi"
    - op: replace
      path: /spec/backups/pgbackrest/repos/0/volume/volumeClaimSpec/resources/requests/storage
      value: "10Gi"