apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: governance-policies-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: policies
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/rprakashg-redhat/rhacm-demos.git
    path: governance/policies
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
