channel: "release-2.8"
approval_strategy: "Automatic"
operator: "advanced-cluster-management"
name: "acm-operator-subscription"
namespace: "open-cluster-management"
source: "redhat-operators"
sourceNamespace: "openshift-marketplace"
hub: "hub"
pullsecret: rh-pullsecret
gitops:
  name: gitops-operator-subscription
  operator: openshift-gitops-operator
  channel: latest
  namespace: openshift-operators