---
apiVersion: v1
kind: Service
metadata:
  name: python-webserver
  labels:
    app: python-webserver
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 8000
  selector:
    app: python-webserver
  type: LoadBalancer
...