- name: cleanup multicluster observability feature
  hosts: localhost
  tasks:
    - name: import static var data
      include_vars:
        dir: vars/static
        ignore_unknown_extensions: True
        extensions:
          - yaml
    
    - name: import dynamic var data
      include_vars:
        dir: vars/dynamic
        ignore_unknown_extensions: True
        extensions:
          - yaml

    - name: deleting multi cluster observability resource
      kubernetes.core.k8s:
        api_key: "{{ token }}"
        state: absent
        resource_definition: "{{ lookup('template', 'templates/multiclusterobservability.yaml.j2') | from_yaml }}"

    - name: deleting metrics object storage secret
      kubernetes.core.k8s:
        api_key: "{{ token }}"
        state: absent
        resource_definition: "{{ lookup('template', 'templates/secret.yaml.j2') | from_yaml }}"

    - name: delete multi cluster hub operator secret pull secret
      command: "oc delete secret multiclusterhub-operator-pull-secret -n open-cluster-management-observability"

    - name: deleting open cluster management observability namespace
      kubernetes.core.k8s:
        state: absent
        api_key: "{{ token }}"      
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: open-cluster-management-observability
          spec: {}

    - name: removing s3 bucket
      amazon.aws.s3_bucket:
        name: grafana-{{ CLUSTER_GUID }}
        aws_access_key: "{{ lookup('ansible.builtin.env', 'AWS_ACCESS_KEY_ID', default='') }}"
        aws_secret_key: "{{ lookup('ansible.builtin.env', 'AWS_SECRET_ACCESS_KEY', default='') }}"
        state: absent
        force: yes
