apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: "postgresql-cluster"
  namespace: openshift-gitops
spec:
  generators:      
  - clusterDecisionResource:
      configMapRef: acm-placement
      labelSelector:
        matchLabels:
          cluster.open-cluster-management.io/placement: devenvironment-placement
      requeueAfterSeconds: 180

  template:
    metadata:
      name: 'postgresql-cluster-{{name}}'
    spec:
      source:
        repoURL: "https://github.com/rprakashg-redhat/rhacm-demos.git"
        path: "applications/postgresql/overlays/dev"
        targetRevision: "HEAD"

      destination:
        namespace: "demos"
        server:  "{{server}}"

      project: default 

  syncPolicy:
    PreserveResourcesOnDeletion: false    
    applicationsSync: sync