---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: book-import-application-set
  namespace: openshift-gitops
spec:
  generators:
  - clusterDecisionResource:
      configMapRef: acm-placement
      labelSelector:
        matchLabels:
          cluster.open-cluster-management.io/placement: ormdemo-dev-placement
      requeueAfterSeconds: 180
  syncPolicy:
    preserveResourcesOnDeletion: false    
  template:
    metadata:
      name: book-import-{{name}}
    spec:  
      project: default

      source:
        repoURL: https://github.com/rprakashg-redhat/rhacm-demos.git
        path: applications/book-import
        targetRevision: main

      destination:
        server: "{{server}}"
        namespace: demos

      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
          - Replace=true
          - ApplyOutOfSyncOnly=true
          - Validate=false
        automated:
          prune: true
          allowEmpty: true
          selfHeal: true
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: book-import-placement
  namespace: openshift-gitops
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: environment
              operator: In
              values:
                - demo
