apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: "ormdemo-service"
  namespace: openshift-gitops
spec:
  generators:      
  - clusterDecisionResource:
      configMapRef: acm-placement
      labelSelector:
        matchLabels:
          cluster.open-cluster-management.io/placement: devenvironment-placement
      requeueAfterSeconds: 180

  template:
    metadata:
      name: 'ormdemo-service-{{name}}'
    spec:
      source:
        repoURL: "https://github.com/rprakashg-redhat/rhacm-demos.git"
        path: "applications/hibernate-reactive-panache-quickstart/service/overlays/dev"
        targetRevision: "HEAD"

      destination:
        namespace: "demos"
        server:  "{{server}}"

      project: default 

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true
    - Replace=true
    - ApplyOutOfSyncOnly=true

    automated:
      prune: true
      allowEmpty: true
      selfHeal: true