apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: scheduler
    patch: |-
      - op: replace
        path: "/spec/template/spec/containers/0/image"
        value:                      "ghcr.io/rprakashg-redhat/eventscheduler@sha256:a0bdf556fc7f8f5c81bba90c7e4532536d19b727da1c90bc5abc70edd298e944"
