apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: check-resource-quota-policy-placementbinding
  namespace: default
placementRef:
  name: check-resource-quota-policy-placementrule
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: check-resource-quota-policy
  kind: Policy
  apiGroup: policy.open-cluster-management.io