apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: add-resource-quota-policy-placementrule
  namespace: default
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
    - {key: environment, operator: In, values: ["production"]}
        