apiVersion: v1
kind: Namespace
metadata:
  name: rhacs-operator
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: "rhacs-operator"
  namespace: "rhacs-operator"
spec:
  channel: stable
  installPlanApproval: Automatic
  name: rhacs-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: "rhacs-operator-operatorgroup"
  namespace: "rhacs-operator"
spec:
  upgradeStrategy: Default
