---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: configuration-policies

policyDefaults:
  namespace: "policies"
  
  pruneObjectBehavior: "DeleteIfCreated"

  standards:
  - "NIST SP 800-53"

  categories:
  - "CM Configuration Management"
  
  controls:
  - "CM-2 Baseline Configuration"
  
  complianceType: "musthave"
  
  evaluationInterval:
    compliant: 1m
    noncompliant: 45s
  
  remediationAction: "inform"
  
  severity: "high"

  placement:
    clusterSelectors:
      environment: "dev"
      vendor: "OpenShift"

policies:    
  - name: install-gatekeeper-operator
    remediationAction: enforce
    manifests:
    - path: ./install-gatekeeper-operator/gatekeeper.yaml

  - name: install-postgresql-operator
    remediationAction: enforce
    manifests:
    - path: ./install-postgresql-operator/postgresql.yaml
  
  - name: container-deny-latest-tag
    remediationAction: enforce
    manifests:
    - path: ./container-deny-latest-tag/constraint.yaml
    - path: ./container-deny-latest-tag/template.yaml

...
