- name: install kustomize
  community.general.homebrew:
    name: kustomize
    state: present

- name: make dir
  file:
    path: ${HOME}/.config/kustomize/plugin/policy.open-cluster-management.io/v1/policygenerator
    state: directory  
    
- name: install policy generator plugin for kustomize
  ansible.builtin.get_url:
    url: https://github.com/stolostron/policy-generator-plugin/releases/download/v1.8.0/darwin-amd64-PolicyGenerator
    dest: ${HOME}/.config/kustomize/plugin/policy.open-cluster-management.io/v1/policygenerator/PolicyGenerator

- name: make it executable
  command: chmod +x ${HOME}/.config/kustomize/plugin/policy.open-cluster-management.io/v1/policygenerator/PolicyGenerator